version: '3.6'

services:
  samp-server:
    image: ${TAG}
    container_name: ${CONTAINER_NAME}
    build: 
      context: .
      args:
        APP_ROOT: ${APP_ROOT}
        TGZ_FILE: ${TGZ_FILE}
    restart: unless-stopped
    ports:
      - ${EXTERNAL_PORT}:7777/tcp
      - ${EXTERNAL_PORT}:7777/udp
    volumes:
      - "./server.cfg:${APP_ROOT}/server.cfg"
    networks:
      - "samp-server-net"

networks:
  samp-server-net:
    name: samp-server-net
